name: flutter_timer_camera
description: A Flutter package that allows you to open the camera and capture images with a timer logic. Perfect for those moments when you need a delay before the shot!
version: 1.0.4
homepage: https://github.com/Blue-Cheesecake/flutter_timer_camera

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Camera
  camera: ^0.10.5+4
  camera_platform_interface: ^2.5.2

  # State Management
  flutter_riverpod: ^2.4.0

  # Generator
  freezed_annotation: ^2.4.1

  # Sliding
  custom_sliding_segmented_control: ^1.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Genarator
  build_runner: ^2.4.6
  freezed: ^2.4.2

flutter:
